"""add timecode and audio_channels to video

Revision ID: 5e25b850e399
Revises: 0001
Create Date: 2026-03-09 15:26:30.907891

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '5e25b850e399'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('timecode', sa.String(length=32), nullable=True))
    op.add_column('videos', sa.Column('audio_channels', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'audio_channels')
    op.drop_column('videos', 'timecode')
    # ### end Alembic commands ###
